
name: 'rental_property_management'
version: '1.0.0'
config-version: 2

profile: 'rental_property_management'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  rental_property_management:
    +enabled: true
    +schema: raw
    +quote_columns: false

models:
  rental_property_management:

    staging:
      +schema: staging
      +materialized: view
      rental_properties:
        base:
          +materialized: ephemeral

    intermediate:
      +schema: intermediate
      +materialized: ephemeral

    marts:
      +schema: marts
      +materialized: table
