rental_property_management:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: hubspot.us-east-1
      user: ssabalain@hubspot.com
      database: dev_db_ssabalain
      warehouse: qa_query_wh
      schema: public
      authenticator: externalbrowser
      client_session_keep_alive: False
    prod:
      type: postgres
      host: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: dbt_{{ env_var('DBT_TARGET') }}
      threads: 1