rental_property_management:
  target: "{{ env_var('DBT_TARGET') }}"
  outputs:
    dev:
      type: postgres
      host: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: dbt_{{ env_var('DBT_TARGET') }}
      threads: 1
    prod:
      type: postgres
      host: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: dbt_{{ env_var('DBT_TARGET') }}
      threads: 1